feat: stop shrinking of small type on larger viewports (#21)
csshugs/FluidMS pull request #22
Opened 2019-12-20 09:26 UTC by csshugs

because:
- when the font-size ratio is increased on larger viewports,
the large type gets larger, but the small type is getting
smaller, which is not what we want

this commit:
- stops the shrinking of smaller type (i.e. smaller than the base
font-size) on larger viewports, when the ratio is changed

2020-01-05 17:48 UTC, fuhlig requested changes
Not quite sure, where the "stopping" happens.

Removal of ratios and line-heights: Part of this PR?

2020-01-05 17:48 UTC, fuhlig commented on src/generic/_generic.ms-custom-properties.scss
> +                        @if not (str-index(#{$scale}, "-")) {
document condition

2020-01-06 08:20 UTC, csshugs commented
The “stopping” is achieved by not generating the respective custom properties for larger viewports (media-queries), so the font-size and line-height keeps the same for smaller type.

2020-01-06 13:47 UTC, fuhlig approved these changes

2020-01-13 08:23 UTC, merged