feat: comply with official else-if notation (#28)
csshugs/FluidMS pull request #30
Opened 2020-04-30 12:30 UTC by csshugs

2020-04-30 21:46 UTC, fuhlig commented
Since the changelog generation & versioning is automated:

I would not consider this a feature. If it fixes a bug (condition was falsy and code not reachable), otherwise I'd consider it a refactoring.

2020-04-30 21:48 UTC, fuhlig requested changes
change type of PR title & commit type to refactor (or fix if it is a bugfix)

2020-05-04 05:24 UTC, csshugs commented
`refactor` it is.

2020-05-04 06:41 UTC, fuhlig approved these changes

2020-05-04 08:35 UTC, merged